les/urls.py
from django.contrib import admin
from django.urls import path, include
from parque.views import index_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    path('parque/', include('parque.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

parque/urls.py
from django.urls import path
from parque.views import (
    ParqueCreateView,
    ParqueListView,
    ParqueDetailView,
    ParqueUpdateView,
    ParqueDeleteView,
    ZonaListView,
    ZonaDeleteView,
    ZonaCreateView,
    ZonaDetailView,
    ZonaUpdateView,
    LugarListView,
    LugarCreateView,
    LugarDetailView,
    LugarDeleteView,
    LugarUpdateView,
    ZonaErrorView,
    LugarErrorView,
)

app_name = 'parque'
urlpatterns = [
    path('', ParqueListView.as_view(), name='parque-list'),
    path('<int:id>/', ParqueDetailView.as_view(), name='parque-detail'),
    path('create/', ParqueCreateView.as_view(), name='parque-create'),
    path('<int:id>/update/', ParqueUpdateView.as_view(), name='parque-update'),
    path('<int:id>/delete/', ParqueDeleteView.as_view(), name='parque-delete'),

    path('<int:id>/zona/', ZonaListView.as_view(), name='zona-list'),
    path('<int:id>/zona/<int:pk>/', ZonaDetailView.as_view(), name='zona-detail'),
    path('<int:id>/zona/<int:pk>/delete/', ZonaDeleteView.as_view(), name='zona-delete'),
    path('<int:id>/zona/create/', ZonaCreateView.as_view(), name='zona-create'),
    path('<int:id>/zona/<int:pk>/update/', ZonaUpdateView.as_view(), name='zona-update'),

    path('<int:id>/zona/<int:pk>/lugar/', LugarListView.as_view(), name='lugar-list'),
    path('<int:id>/zona/<int:pk>/lugar/<int:lugar>/', LugarDetailView.as_view(), name='lugar-detail'),
    path('<int:id>/zona/<int:pk>/lugar/<int:lugar>/delete/', LugarDeleteView.as_view(), name='lugar-delete'),
    path('<int:id>/zona/<int:pk>/lugar/create/', LugarCreateView.as_view(), name='lugar-create'),
    path('<int:id>/zona/<int:pk>/lugar/<int:lugar>/update/', LugarUpdateView.as_view(), name='lugar-update'),

    path('<int:id>/zona/create/erro/', ZonaErrorView.as_view()),
    path('<int:id>/zona/<int:pk>/lugar/create/erro/', LugarErrorView.as_view()),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About</h1>

<h3>{{ title|capfirst|upper }}</h3> <!--capfirst always put the first letter on CAPS, upper puts all letters on CAPS-->
<p>This is a template</p>

{{ my_html|safe }}

<p>
{{ my_number }}
{{ my_list }}
</p>

<ul>
    <li>Item 1</li>
    <li>Item 2</li>
</ul>

<ul>
    {% for my_sub_item in my_list %}
        {% if my_sub_item == 312 %}
            <li>{{ forloop.counter }} - {{ my_sub_item|add:22 }}</li>
        {% elif my_sub_item == "abc" %}
            <li>Hello world</li>
        {% else %}
            <li>{{ forloop.counter }} - {{ my_sub_item }}</li>
        {% endif %}
    {% endfor %}
</ul>


{% endblock %}

templates/base.html
<!doctype html>
<html>
<head>
    <title>LES</title>
    </head>
<body>
    <!--<h1>This is a navbar</h1>-->
    {% include 'navbar.html' %}
    {% block content %}
    replace me
    {% endblock %}
    </body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>Contact</h1>
<p>This is a template</p>
{% endblock content %}

templates/erro_lugar.html
<h1>Esta zona já contém o número máximo de lugares</h1>

<br>
        
<form action="../../">
    <input type="submit" value="Go Back" />
</form>

templates/erro_zona.html
<h1>Este parque já contém o número máximo de zonas</h1>

<br>
        
<form action="../../">
    <input type="submit" value="Go Back" />
</form>

templates/home.html
{% extends 'base.html' %} <!--must be on the line 1-->

<!--
First test

<h1>Hello World</h1>
{{ request.user }} give us the user name
{{ request.user.is_authenticated }} True is logged, False if not
<p>This is a template</p>
-->

{% block content %}
    <div>
      <div class="section">
        <div class="columns">
          <div class="column is-7">
            <h1 class="title has-text-centered">Nova plataforma</h1>
            <h1 class="subtitle is-5 has-text-centered">
              Simples, Intuitivo, Limpo.
            </h1>
            <p>
              A plataforma online do Dia Aberto foi renovada pelos alunos em
              âmbito do curso de Licenciatura de Engenharia Informática.
            </p>
          </div>
          <div class="column is-4">
          </div>
        </div>
      </div>
      <div class="hero is-light">
        <div class="hero-body">
          <div class="columns">
            <div class="column is-8">
              <p>2019 Dia Aberto por <a>Grupo 9</a></p>
              <small>
                Contacto de suporte:
                <a href="">suporte.dia.aberto@ualg.pt</a>
              </small>
            </div>
            <div class="column">
            </div>
            <div class="column is-1" />
          </div>
        </div>
      </div>
    </div>

    <form action="parque/">
      <p>PARQUES:</p>
      <input type="submit" value="Parques" />
  </form>
{% endblock %}

templates/navbar.html
<style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      border: 1px solid #e7e7e7;
      background-color: #f3f3f3;
    }
    
    li {
      float: left;
    }
    
    li a {
      display: block;
      color: #666;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }
    
    li a:hover:not(.active) {
      background-color: #ddd;
    }
    
    li a.active {
      color: white;
      background-color: #04AA6D;
    }
    </style>
    </head>
    <body>
    
    <ul>
      <li><a class="active" href="#home">Home</a></li>
      <li><a href="#news">News</a></li>
      <li><a href="#contact">Contact</a></li>
      <li><a href="#about">About</a></li>
    </ul>

templates/table_lugar.html
<a href="{% url 'parque:lugar-detail' id=record.zonaid.parqueid.id pk=record.zonaid.id lugar=record.id %}">Ver Mais</a>

templates/table_zona.html
<a href="{% url 'parque:zona-detail' id=record.parqueid.id pk=record.id %}">Ver Mais</a>